version: '3.3'
services:

  frontend:
    container_name: foodgram-frontend
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    container_name: foodgram-backend
    build:
      context: ../backend
    volumes:
      - ../backend/:/app/
      - ../data:/app/data/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../backend/.env

  db:
    container_name: foodgram-db
    image: postgres:14.0-alpine  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/.env

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  media_value: 